### ISSUE TITLE
Use test dataset that we made at hackathon?

### ISSUE THREAD

**Issue by nickmorales** [plantbreeding/BrAPI-Dataset#1]
For loading data into this data model can you please use the test dataset that we made in the hackathon here: https://docs.google.com/spreadsheets/d/1tTXwLANWbgZU29UcuUWbCGiPJnO1KY93ojup6hy5094/edit#gid=485098686

I think eventually that test dataset will be available here also https://github.com/plantbreeding/brapiTS/tree/master/inst/apps/brapi/data

**Comment by gcornut** [comment]
Yes I used these to write the CSV in the data/crop1 folder.
I had to split them by table though to have a direct loading from CSV to table without any transformation.

We could transform the Google spreadsheet into these split CSV but it seems it could be very complicated. I thought, once the full dataset is integrated into the database, we could easily export it back to CSV and then load them in the Google spreadsheet.
